font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: LMMonoCaps10
    style: Regular

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: LMMonoCaps10
    style: Oblique

  size: 12

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: PageUp, mods: Shift, action: ScrollPageUp }
  - { key: PageDown, mods: Shift, action: ScrollPageDown }
  - { key: Home, mods: Shift, action: ScrollToTop }
  - { key: End, mods: Shift, action: ScrollToBottom }
