public-key = "age14993nespmwgcsev4tu2mx7h32p326yuz0lekpna8gkw0tw98hf8q8yedp5"
keyfile = "~/.config/kbs2/key.wrapped"
agent-autostart = true
wrapped = true
store = "~/.kbs2-store"
pinentry = "pinentry"
error-hook = "~/.config/kbs2/hooks/error-hook-notify"
reentrant-hooks = false

[[generators]]
name = "default"
alphabets = [
  "abcdefghijklmnopqrstuvwxyz",
  "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  "0123456789",
  "(){}[]-_+=",
]
length = 16

[commands.new]
generate-on-empty = true
post-hook = "~/.config/kbs2/hooks/push-repo"

[commands.pass]
clipboard-duration = 10
clear-after = true
x11-clipboard = "Clipboard"
clear-hook = "~/.config/kbs2/hooks/pass-clear-notify"

[commands.edit]
editor = "subl -w"
post-hook = "~/.config/kbs2/hooks/push-repo"

[commands.rm]
post-hook = "~/.config/kbs2/hooks/push-repo"

[commands.ext.dmenu-pass]
notify-username = true

[commands.ext.choose-pass]
notify-username = true
