#!/usr/bin/env bash

# aaa: auto albumart

function installed {
	cmd=$(command -v "${1}")

	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

installed albumart || { echo "Missing albumart." ; exit ; }

artist=$(basename "${PWD}")
albums=($(find . -maxdepth 1 -mindepth 1 -type d -printf '%f\n'))

[[ -z "${albums[*]}" ]] && { printf "No albums found.\n" ; exit ; }

echo "Artist: ${artist}"
echo "Albums: ${albums[*]}"

read -e -p "Continue? (y/N) " prompt

[[ "${prompt}" =~ (y|Y) ]] || exit

pushd . > /dev/null

for album in "${albums[@]}"; do
	pushd "${album}" > /dev/null
	albumart "${artist} - ${album}" 2> /dev/null
	popd > /dev/null
done

popd > /dev/null
