#!/usr/bin/env ruby
# frozen_string_literal: true

# brewnav: quick dmenu integration for my frequent homebrew links

require "open3"

BROWSER = ENV["BROWSER"] || "firefox"
DMENU_EXEC = "dmenu -i -p brewnav"
URL_MAP = {
  "Homebrew/brew" => "https://github.com/Homebrew/brew/",
  "woodruffw/brew" => "https://github.com/woodruffw/brew/",
  "Homebrew/core" => "https://github.com/Homebrew/homebrew-core/",
  "woodruffw/core" => "https://github.com/woodruffw/homebrew-core/",
  "core-pulls" => "https://github.com/Homebrew/homebrew-core/pulls/",
  "brew-pulls" => "https://github.com/Homebrew/brew/pulls/",
}.freeze

def browse(url)
  system BROWSER, url
end

def dmenu(options)
  opts = options.join("\n")
  stdout, = Open3.capture2 DMENU_EXEC, stdin_data: opts
  stdout.chomp
end

url = URL_MAP[dmenu(URL_MAP.keys)]

browse url if url
