#!/usr/bin/env ruby
# frozen_string_literal: true

# bug-roommates: send my roommates something via groupme

require "json"
require "open3"
require "securerandom"

URL = "https://api.groupme.com/v3/groups/%<group_id>s/messages"

group_id = `kbsecret env -s keys -v groupme-roommate-id`.chomp
token = `kbsecret env -s keys -v groupme-api`.chomp
url = URL % { group_id: group_id }
header_flag = "--header 'X-Access-Token: #{token}'"

uuid = SecureRandom.uuid
text = ARGF.read.chomp

request = {
  message: {
    source_guid: uuid,
    text: text,
  },
}

Open3.popen2("curl -X POST #{header_flag} -d @- #{url}") do |stdin, stdout, _|
  stdin.write request.to_json
  stdin.close
  stdout.read
  stdout.close
end
