#!/usr/bin/env ruby
# frozen_string_literal: true

# bug-roommates: send my roommates something via groupme

require "json"
require "open3"
require "securerandom"

URL = "https://api.groupme.com/v3/groups/%<group_id>s/messages"

group_id = `kbsecret env -s keys -v groupme-roommate-id`.chomp
token = `kbsecret env -s keys -v groupme-api`.chomp
url = URL % { group_id: group_id }

uuid = SecureRandom.uuid
text = ARGF.read.chomp

request = {
  message: {
    source_guid: uuid,
    text: text,
  },
}

curl = ["curl", "-X", "POST", "--header", "X-Access-Token: #{token}", "-d", request.to_json, url]

exec(*curl)
