#!/usr/bin/env bash

# cart.sh: compile and run test.c

if [[ ! -f "./test.c" ]]; then
	echo "No test.c found. Exiting."
	exit 1
else
	gcc -Wall -Wextra -pedantic -std=c99 test.c -o test && ./test
fi
