#!/usr/bin/env bash

# colormake: primitive make colorizing.

# what an ugly command.
# one of these days i'll make it better.
make $@ 2>&1 | sed -e 's/\bwarning/\x1b[33m&\x1b[0m/'\
				-e 's/\berror/\x1b[31m&\x1b[0m/' \
				-e 's/\bgcc/\x1b[36m&\x1b[0m/' \
				-e 's/\bcc/\x1b[36m&\x1b[0m/' \
				-e 's/\bclang/\x1b[36m&\x1b[0m/' \
				-e 's/\brm/\x1b[32m&\x1b[0m/' \
				-e 's/\bcd/\x1b[32m&\x1b[0m/' \
				-e 's/\bld/\x1b[32m&\x1b[0m/' \
				-e 's/\binstall/\x1b[32m&\x1b[0m/' \
				-e 's/\bmake/\x1b[34m&\x1b[0m/'
