#!/usr/bin/env bash

# colormake: primitive make colorizing.

# what an ugly command.
# one of these days i'll make it better.
make $@ 2>&1 | sed -e 's/\bWARNING/\x1b[33m&\x1b[0m/i'\
				-e 's/\bERROR/\x1b[31m&\x1b[0m/i' \
				-e 's/\bGCC/\x1b[36m&\x1b[0m/i' \
				-e 's/\bCC/\x1b[36m&\x1b[0m/i' \
				-e 's/\bCLANG/\x1b[36m&\x1b[0m/i' \
				-e 's/\bRM/\x1b[32m&\x1b[0m/i' \
				-e 's/\bCD/\x1b[32m&\x1b[0m/i' \
				-e 's/\bLD/\x1b[32m&\x1b[0m/i' \
				-e 's/\bINSTALL/\x1b[32m&\x1b[0m/i' \
				-e 's/\bMAKE/\x1b[34m&\x1b[0m/i'
