#!/usr/bin/env bash

# cron-shunt: loads the environment, then evals the arguments

# load API key files if they exist
if [[ -d ~/.api-keys ]] ; then
  for keyfile in ~/.api-keys/*
  do
    source "${keyfile}"
  done
fi

eval "$@"
