#!/usr/bin/env bash

# cron-shunt: loads the environment, then evals the first argument

[ `uname` = "Linux" ] && source ~/.bashrc
[ `uname` = "Darwin" ] && source ~/.bash_profile

eval "$HOME/scripts/$1"
