#!/usr/bin/env bash

# ezsshfs: wrap sshfs to make it a little nicer to use

function die {
  echo "Error: $*" >&2
  exit 1
}

function ensure {
  "$@" \
    || die "Failed to run '$*'. Aborting."
}

function installed {
  cmd=$(command -v "${1}")

  [[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
  return ${?}
}

function plat_umount {
  if installed fusermount; then
    fusermount -u "${1}" 2> /dev/null
  else
    umount "${1}"
  fi
}

[[ -f ~/.config/ezsshfsrc ]] || die "Missing ~/.config/ezsshfsrc"

declare -A mntmap
source ~/.config/ezsshfsrc

ensure installed "selecta"
ensure installed "sshfs"

key=$(printf "%s\n" "${!mntmap[@]}" | selecta)

[[ -n "${key}" && -n "${mntmap[${key}]}" ]] || die "Missing or no such key."

read -ra paths <<< "${mntmap[${key}]}"
host="${paths[0]}"
spath="${paths[1]}"
mpath="${paths[2]}"
mkdir -p "${mpath}"

if [[ "${1}" = "-u" ]]; then
  plat_umount "${mpath}"
else
  sshfs "${host}:${spath}" "${mpath}"
fi
