#!/usr/bin/env bash

# ezsshfs: wrap sshfs to make it a little nicer to use

die() {
  echo "Error: $*" >&2
  exit 1
}

ensure() {
  "$@" \
    || die "Failed to run '$*'. Aborting."
}

installed() {
  cmd=$(command -v "${1}")

  [[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
  return ${?}
}

[[ -f ~/.config/ezsshfsrc ]] || die "Missing ~/.config/ezsshfsrc"

declare -A mntmap
source ~/.config/ezsshfsrc

ensure installed "selecta"
ensure installed "sshfs"
ensure installed "fusermount"

key=$(printf "%s\n" "${!mntmap[@]}" | selecta)

[[ -n "${key}" && -n "${mntmap[${key}]}" ]] || die "Missing or no such key."

paths=(${mntmap[${key}]})
host="${paths[0]}"
spath="${paths[1]}"
mpath="${paths[2]}"
mkdir -p "${mpath}"

if [[ "${1}" = "-u" ]]; then
  fusermount -u "${mpath}" 2> /dev/null
else
  sshfs "${host}:${spath}" "${mpath}"
fi
