#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "json"

len = STDIN.read(4).unpack1("L")
url = JSON.parse(STDIN.read(len))["url"]

system "notify-send", "ff2mpv", url

pid = spawn "mpv", "--no-terminal", "--", url, in: :close, out: "/dev/null", err: "/dev/null"
Process.detach pid
