#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "json"

len = STDIN.read(4).unpack("L").first
url = JSON.parse(STDIN.read(len))["url"]

system "notify-send", "ff2mpv", url

pid = spawn "mpv", "--", url, in: :close, out: :close, err: :close
Process.detach pid
