#!/usr/bin/env ruby
# frozen_string_literal: true

# fwuf: Fix weird Unicode representations in filenames
# Replaces "#U\d{4}" representations with their UTF-8 codepoints.

filename = ARGV.shift

abort("Missing filename.") if filename.nil?
abort("No such file.") unless File.exist?(filename)

fixed = filename.gsub(/#U(\h{4})/) { [$1.to_i(16)].pack("U") }

File.rename(filename, fixed)
