#!/usr/bin/env ruby
# frozen_string_literal: true

# geocode: print a more formal address for the given query

require "net/http"
require "json"
require "cgi"

URL = "https://maps.googleapis.com/maps/api/geocode/json?address=%<address>s&key=%<key>s"

coords = ARGV.first == "-c"
ARGV.shift if coords

key = `kbs2 env -v google-geocoding-api-key`.chomp!
query = ARGV.join " "
url   = URL % { address: CGI.escape(query), key: CGI.escape(key) }

abort("Missing query.") if query.empty?

begin
  resp = JSON.parse(Net::HTTP.get(URI(url)))
  abort("Error: #{resp["status"]}") if resp["status"] != "OK"

  result = resp["results"].first
  if coords
    puts "#{result["geometry"]["location"]["lat"]}, #{result["geometry"]["location"]["lng"]}"
  else
    puts result["formatted_address"]
  end
rescue StandardError => e
  abort("Something exploded: #{e}.")
end
