#!/usr/bin/env bash

# ghbrowse: quickly navigate to a github repo i've recently worked on

function fail {
    >&2 echo "Fatal: ${*}."
    exit 1
}

read -ra orgs < <(git config ghbrowse.orgs)
if [[ "${#orgs[@]}" -eq 0 ]]; then
    read -ra orgs < <(git config github.user)
fi

[[ "${#orgs[@]}" -eq 0 ]] && fail "missing github.user and ghbrowse.orgs in git config"

repos=()
for org in "${orgs[@]}"; do
    url="https://api.github.com/users/${org}/repos?type=all&sort=pushed"
    mapfile -t new_repos < <(curl --silent "${url}" | jq -r ".[] | .full_name")
    repos=("${repos[@]}" "${new_repos[@]}")
done

repo=$( (IFS=$'\n'; rofi -dmenu -p ghbrowse <<< "${repos[*]}") )

[[ -z "${repo}" ]] && exit

"${BROWSER:-firefox}" "https://github.com/${repo}"
