#!/usr/bin/env ruby
# frozen_string_literal: true

# git-gem-release-tag: Create a git tag for a Ruby namespace's version,
#  build a new gem for that tag, and push that gem to Rubygems.

namespace = ARGV.shift || abort("Give me a namespace to check.")
specname  = namespace.downcase

# __dir__ doesn't work because `git` doesn't cwd to the project for some reason
root = `pwd`.chomp

# any of these might have our version constant in them!
glob = File.join(root, "lib", "*.rb")
Dir[glob].each { |f| require_relative f }

tags = `git tag`.split
version = Object.const_get(namespace)::VERSION

abort("Did you forget to update #{namespace}::VERSION?") if tags.include?(version)

gemspec = File.join(root, "#{specname}.gemspec")
abort("Couldn't find #{specname}.gemspec") unless File.file?(gemspec)

# you'd better hope each of these steps works!
system "git tag #{version}"
system "git push origin #{version}"
system "gem build #{specname}"
system "gem push #{specname}-#{version}.gem"
