#!/usr/bin/env ruby
# frozen_string_literal: true

# git-shard-release-tag: Create a git tag for a Crystal shard's version.

def act(s)
  if ARGV.include? "--dry-run"
    puts s
  else
    system s
  end
end

abort("No shards.yml?") unless File.exist?("shards.yml")

version = `shards version`.chomp
tags = `git tag`.split

abort("Did you forget to bump your version?") if tags.include?(version)

act "git tag #{version}"
act "git push origin #{version}"
