#!/usr/bin/env bash

# jellyfin: open firefox to jellyfin.
# this used to be an alias, but i want it to show up in dmenu.

function installed() {
  cmd=$(command -v "${1}")

  [[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
  return ${?}
}

function notify() {
  notify-send --expire-time=3000 info "${*}"
}

installed firefox || { notify "$(basename "${0}") needs 'firefox'." ; exit 1 ; }

i3-msg 'exec firefox -new-window "https://thing-in-itself.net/jellyfin"'
