#!/usr/bin/env bash

# kbs2-dmenu-pass: List all kbs2 logins in dmenu, feed the selected one into the clipboard.

labels=$(kbs2 list -k login)
label=$(dmenu -p kbs2 <<< "${labels}")

kbs2 pass -c "${label}"
