#!/usr/bin/env ruby

# kbsecret-snip: quickly select kbsecret snippet records using selecta

require "kbsecret"
require "slop"
require "open3"

opts = Slop.parse suppress_errors: true do |o|
  o.banner = <<~EOS
    Quickly select a snippet.

    Usage:
      kbsecret snip [--session <name>]

    Examples:
      kbsecret snip
      kbsecret snip -s dev-team
  EOS

  o.string "-s", "--session", "the session name", default: :default
  o.bool "-e", "--execute", "execute the snippet instead of printing it"

  o.on "-h", "--help" do
    puts o
    exit
  end

  o.on "--introspect-flags" do
    puts o.options.flat_map { |o| o.flags }.join "\n"
    exit
  end
end

sess_name = opts[:session]

unless KBSecret::Config.session? sess_name
  abort "Fatal: Unknown session: '#{sess_name}'."
end

session = KBSecret::Session.new label: sess_name

snippets = session.records.select { |r| r.type == "snippet" }

selections = snippets.map { |s| "#{s.label} - #{s.code}" }
selection_map = selections.zip(snippets).to_h

selection = Open3.popen2("selecta") do |stdin, stdout, _|
  stdin.write selections.join("\n")
  stdin.close
  stdout.read
end.chomp

code = selection_map[selection]&.code

return unless code

if opts.execute?
  exec code
else
  puts code
end
