#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-dmenu-pass: List all kbsecret logins in dmenu, take the
# selected one and feed the associated password into the clipboard.

require "kbsecret"
require "open3"

begin
  require "clipboard"
rescue LoadError
  abort "Fatal: You need the clipboard gem: `gem install clipboard`"
end

include KBSecret

CLI.die "Missing dependency: `dmenu`" unless CLI.installed? "dmenu"

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage: kbsecret dmenu-pass [options]
    HELP

    o.string "-s", "--session", "the session to load from", default: :default
  end

  c.ensure_session!
end

records = cmd.session.records :login

label, = Open3.capture2("dmenu -p kbsecret", stdin_data: records.join("\n"))

label.chomp!

abort if label.empty? || !cmd.session.record?(label)

Clipboard.copy cmd.session[label].password
