#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-recovery: manage recovery records

require "kbsecret"

include KBSecret

EMPTY_RECORD_WARNING = <<~WARN
  There are no more recovery codes left in this record.
  You can load more via `kbsecret recovery load`.
WARN

cmd = CLI.create do |c|
  c.slop cmds: %w[load next] do |o|
    o.banner = <<~HELP
      Usage: kbsecret recovery [options] <load|next> <label>
    HELP

    o.string "-s", "--session", "the session to search in", default: :default
  end

  c.dreck do
    string :command
    string :label
  end

  c.ensure_session!
end

recovery = cmd.session[cmd.args[:label]]

cmd.die "No such record." unless recovery
cmd.die "'#{recovery}' is not a recovery record." unless recovery.type == :recovery

case cmd.args[:command]
when "load"
  cmd.info "Enter recovery codes to load, one per line. Terminate input with ^D."

  codes = STDIN.read.lines.map!(&:strip).reject(&:empty?)
  recovery.load(*codes)
when "next"
  code = recovery.next

  if code
    puts code
    cmd.warn EMPTY_RECORD_WARNING if recovery.codes.empty?
  else
    cmd.die EMPTY_RECORD_WARNING
  end
else
  cmd.die "Unknown subcommand: '#{cmd.args[:command]}'."
end
