#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-todo-list: list kbsecret todo records more flexibly

require "kbsecret"
require "slop"

include KBSecret

cmd = CLI.new do
  slop cmds: %w[started suspended completed] do |o|
    o.banner = <<~EOS
      Usage:
        kbsecret todo-list <started|suspended|completed>
    EOS

    o.string "-s", "--session", "the session to list from", default: :default
    o.bool "-d", "--detail", "list the full todo text"
  end

  dreck do
    string :subcommand
  end

  ensure_session!
end

session      = Session.new label: cmd.opts[:session]
todo_records = session.records :todo
subcommand   = cmd.args[:subcommand]

selected_records = case subcommand
                   when "started"
                     todo_records.select(&:started?)
                   when "suspended"
                     todo_records.select(&:suspended?)
                   when "completed"
                     todo_records.select(&:completed?)
                   else
                     CLI.die "Unknown action: '#{subcommand}'."
                   end

selected_records.each do |record|
  if cmd.opts.detail?
    puts "#{record.label} - #{record.todo}"
  else
    puts record.label
  end
end
