#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-zen-login: Add a login record to kbsecret via a Zenity form.

def zenity_form(text, entries, secrets)
  args = [
    "zenity",
    "--title=kbsecret",
    "--forms",
    "--text=#{text}",
    "--separator=\x01",
  ]

  args.concat(entries.map { |e| "--add-entry=#{e}" })
  args.concat(secrets.map { |s| "--add-password=#{s}" })

  inputs = IO.popen(args)
             .read
             .split("\x01")
             .map(&:chomp)
             .reject(&:empty?)

  return if inputs.size != (entries.size + secrets.size)

  (entries + secrets).zip(inputs).to_h
end

if ARGV.include?("--help")
  puts <<~EOS
    Create a new login record using a Zenity form.

    Usage:
      kbsecret zen-login
  EOS

  exit
end

fields = zenity_form("New Login", %w[Label Username], %w[Password])

return unless fields

args = [
  "kbsecret",
  "new",
  "-f",
  "login",
  fields["Label"],
  fields["Username"],
  fields["Password"],
]

system(*args)
