#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-yad-login: Add a login record to kbsecret via a YAD form.

require "kbsecret"

include KBSecret

SEPARATOR = "\x01"

FIELDS = {
  "Label" => "",
  "Username" => "",
  "Password" => "H",
  "Session" => "CB",
}.freeze

FIELD_DEFAULTS = [
  "",
  "",
  Generator.new.secret,
  Config.session_labels.join(SEPARATOR),
].freeze

SKELETON_YAD_ARGS = [
  "yad",
  "--form",
  "--separator=#{SEPARATOR}",
  "--item-separator=#{SEPARATOR}",
  "--text-align=left",
  "--text=New Login",
  "--title=kbsecret",
].freeze

CLI.die "Missing dependency: `yad`" unless CLI.installed? "yad"

CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret yad-login [options]
    HELP
  end
end

yad_args = SKELETON_YAD_ARGS \
           + FIELDS.map { |k, v| "--field=#{k}:#{v}" } \
           + FIELD_DEFAULTS

inputs = IO.popen(yad_args)
           .read
           .split(SEPARATOR)
           .map(&:chomp)
           .reject(&:empty?)

return if inputs.size != FIELDS.size

fields = FIELDS.keys.zip(inputs).to_h
sess   = Session.new label: fields["Session"]

sess.add_record(:login, fields["Label"], fields["Username"], fields["Password"], overwrite: true)
