#!/usr/bin/env bash

# kbsecret-dmenu-pass: List all kbsecret logins in dmenu, take the
# selected one and feed the associated password into the clipboard.

label=$(kbsecret list -t login | dmenu)

[[ -n "${label}" ]] && kbsecret pass -c "${label}"
