#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-yad-login: Add a login record to kbsecret via a YAD form.

if ARGV.include?("--help")
  puts <<~EOS
    Create a new login record using a YAD form.

    Usage:
      kbsecret yad-login
  EOS

  exit
end

SEPARATOR = "\x01"

FIELDS = {
  "Label" => "",
  "Username" => "",
  "Password" => "H",
  "Session" => "CB",
}.freeze

FIELD_DEFAULTS = [
  "",
  "",
  "",
  `kbsecret sessions`.split.join(SEPARATOR),
].freeze

SKELETON_YAD_ARGS = [
  "yad",
  "--form",
  "--separator=#{SEPARATOR}",
  "--item-separator=#{SEPARATOR}",
  "--text-align=left",
  "--text=New Login",
  "--title=kbsecret",
].freeze

yad_args = SKELETON_YAD_ARGS \
           + FIELDS.map { |k, v| "--field=#{k}:#{v}" } \
           + FIELD_DEFAULTS

inputs = IO.popen(yad_args)
           .read
           .split(SEPARATOR)
           .map(&:chomp)
           .reject(&:empty?)

return if inputs.size != FIELDS.size

fields = FIELDS.keys.zip(inputs).to_h

kb_args = [
  "kbsecret",
  "new",
  "-fs",
  fields["Session"],
  "login",
  fields["Label"],
  fields["Username"],
  fields["Password"],
]

exec(*kb_args)
