#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-qr: Generate and display a QR code containing the password for a login record.

require "kbsecret"
require "open3"
require "tempfile"

include KBSecret

DEPS = %w[qrencode feh].freeze
QRENCODE_ARGS = %w[qrencode -s 12 -o -].freeze

DEPS.each do |dep|
  CLI.die "Missing dependency: `#{dep}`" unless CLI.installed? dep
end

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage: kbsecret qr [options] <label>
    HELP

    o.string "-s", "--session", "the session to load from", default: :default
  end

  c.dreck do
    string :label
  end

  c.ensure_session!
end

record = cmd.session[cmd.args[:label]]

cmd.die "No such record." unless record
cmd.die "'#{record}' is not a login record." unless record.type == :login

png_data, status = Open3.capture2(*QRENCODE_ARGS, stdin_data: record.password)

cmd.die "qrencode exited with status #{status.exitstatus}" unless status.success?

_, status = Open3.capture2("feh", "-", stdin_data: png_data)

cmd.die "feh exited with #{status.exitstatus}" unless status.success?
