#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-snip: quickly select kbsecret snippet records using selecta

require "kbsecret"
require "slop"
require "open3"

trap(:INT) { exit! }

opts = Slop.parse suppress_errors: true do |o|
  o.banner = <<~EOS
    Quickly select a snippet.

    Usage:
      kbsecret snip [--session <name>]

    Examples:
      kbsecret snip
      kbsecret snip -s dev-team
  EOS

  o.string "-s", "--session", "the session name", default: :default
  o.bool "-e", "--execute", "execute the snippet instead of printing it"

  o.on "-h", "--help" do
    puts o
    exit
  end

  o.on "--introspect-flags" do
    puts o.options.flat_map(&:flags).join "\n"
    exit
  end
end

session       = KBSecret::CLI.ensure_session opts[:session]
snippets      = session.records :snippet
selections    = snippets.map { |s| "#{s.label} - #{s.code}" }
selection_map = selections.zip(snippets).to_h

selection = Open3.popen2("selecta") do |stdin, stdout, _|
  stdin.write selections.join("\n")
  stdin.close
  stdout.read
end.chomp

code = selection_map[selection]&.code

return unless code

if opts.execute?
  exec code
else
  puts code
end
