#!/usr/bin/env ruby
# frozen_string_literal: true

# kbsecret-snip: quickly select kbsecret snippet records using selecta

require "kbsecret"
require "open3"

include KBSecret

trap(:INT) { exit! }

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret snip [--session <session>]
    HELP

    o.string "-s", "--session", "the session to search in", default: :default
    o.bool "-e", "--execute", "execute the snippet instead of printing it"
  end

  c.ensure_session!
end

snippets      = cmd.session.records :snippet
selections    = snippets.map { |s| "#{s.label} - #{s.code}" }
selection_map = selections.zip(snippets).to_h
output,       = Open3.capture2 "selecta", stdin_data: selections.join("\n")
selection     = output.chomp

code = selection_map[selection]&.code

return unless code

if cmd.opts.execute?
  exec code
else
  puts code
end
