#!/usr/bin/env ruby

# kbsecret-zen-login: Add a login record to kbsecret via a Zenity form.

require "kbsecret"

def zenity_form(text, entries, secrets)
  args = [
    "zenity",
    "--title=kbsecret",
    "--forms",
    "--text=#{text}",
    "--separator=\x01",
  ]

  args.concat entries.map { |e| "--add-entry=#{e}" }
  args.concat secrets.map { |s| "--add-password=#{s}" }

  stdout = IO.popen(args)
  inputs = stdout.read.split("\x01").map(&:chomp).reject(&:empty?)
  stdout.close

  return if inputs.size != (entries.size + secrets.size)

  Hash[(entries + secrets).zip(inputs)]
end

fields = zenity_form("New Login", ["Label", "Username"], ["Password"])

return unless fields

args = [
  "kbsecret",
  "new",
  "-f",
  "login",
  fields["Label"],
  fields["Username"],
  fields["Password"],
]

system *args
