#!/usr/bin/env bash

# last-photo: grab the last N photos taken on my phone

set -o pipefail

die() {
  echo "Error: $*" >&2
  exit 1
}

ensure() {
  "$@" \
    || die "Failed to run '$*'. Aborting."
}

nphotos="${1:-1}"
dest="${2:-${PWD}}"
dev=$(ensure gvfs-mount --list \
	| grep "mtp ->" \
	| awk '{ print $4 }')
ppath="${dev}Internal%20shared%20storage/DCIM/Camera/"

photos=$(ensure gvfs-ls "${ppath}" \
		| tail -n "${nphotos}")

for photo in ${photos}; do
	ensure gvfs-copy "${ppath}/${photo}" "${dest}"
done
