#!/usr/bin/awk -f

# linecheck: report lines exceeding 80 characters in files

BEGIN {
	max = 80
}

{
	if (length($0) > max)
	{
		printf "%s:%d exceeds %d characters.\n", FILENAME, FNR, max
	}
}

END {
	exit 0
}
