#!/usr/bin/env bash

# microsoft-mouse: set mouse preferences (speed and scroll speed) for my crappy wireless mouse

device="Microsft Microsoft Wireless Optical Desktop"

# exit unless the mouse is actually plugged in
xinput --list --short | grep -q "${device}" || exit

# our device id matches our device name, is a pointer, and is matched by id=\d+
id=$(xinput --list --short \
    | grep -e "${device}" \
    | grep pointer \
    | sed -n 's/.*id=\([0-9]\+\).*/\1/p')

xset mouse 2 0
xinput set-prop "${id}" 'Evdev Scrolling Distance' 1 1 1

# As far as I can tell, this is the mapping:
# 1 -> 1 (left click)
# 8 -> 2 (back button -> middle click)
# 3 -> 3 (right click)
# 4 -> 4 (scroll up)
# 5 -> 5 (scroll down)
# 6 -> 6 (scroll left)
# 7 -> 7 (scroll right)
# 2 -> 8 (middle click -> back button)
# 9 -> 9 (forward button)
# 11, 12, 13 -> ???
xmodmap -e "pointer = 1 8 3 4 5 6 7 2 9 10 11 12 13"
