#!/bin/sh
xrandr --output DisplayPort-1 --mode 1920x1080 --pos 0x0 --rotate left \
    --output DisplayPort-0 --off \
    --output DVI-0 --mode 1680x1050 --pos 1080x0 --rotate normal \
    --output HDMI-0 --mode 1920x1080 --pos 2760x0 --rotate normal

xrandr --output DVI-0 --primary
