#!/bin/sh

# NOTE: --mode 1920x1080 stopped working for unclear reasons on DisplayPort-1.
# 1920x1080_60.00 is a custom mode, added like this:
# xrandr --newmode "1920x1080_60.00" 172.80 1920 2040 2248 2576 1080 1081 1084 1118 -HSync +Vsync
# xrandr --addmode DisplayPort-1 1920x1080_60.00

xrandr --output DisplayPort-1 --mode 1920x1080_60.00 --pos 0x0 --rotate left \
    --output DisplayPort-0 --off \
    --output DVI-0 --mode 1680x1050 --pos 1080x0 --rotate normal \
    --output HDMI-0 --mode 1920x1080 --pos 2760x0 --rotate normal

xrandr --output DVI-0 --primary
