#!/usr/bin/env bash

# mumble-insecure: Run the mumble client with a less secure OpenSSL config
# See: https://bugs.launchpad.net/ubuntu/+source/gnutls28/+bug/1856428

set -eo pipefail

read -r -d '' OPENSSL_CONF_INI <<'OPENSSL_CONF'
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT@SECLEVEL=1
OPENSSL_CONF

OPENSSL_CONF=<(echo "${OPENSSL_CONF_INI}") mumble
