#!/usr/bin/env bash

# music-clean: remove common cruft files accumulated in a music directory
# additionally, if mp3val is installed, fix mp3 errors

[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && exit 1 # we need bash >= 4.0

function installed() {
	local cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

shopt -s globstar

music_dir="${HOME}/music"

cruft=("${music_dir}"/**/*.{cue,txt,txt,log,m3u,nfo,bak,sfv})
# mp3s=("${music_dir}"/**/*.mp3)

for junk in "${cruft[@]}"; do
	rm -f "${junk}"
done

# if installed mp3val; then
# 	for mp3 in "${mp3s[@]}"; do
# 		mp3val -f "${mp3}"
# 	done
# fi
