#!/usr/bin/env bash

# music-backup: use rsync to back ~/music up to /media/backup/music

function installed {
	cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

installed rsync || (echo "Fatal: Missing rsync." ; exit 1)
[[ -d /media/backup ]] || (echo "Fatal: No backup drive." ; exit 2)
[[ -d ~/music ]] || (echo "Fatal: No music directory." ; exit 3)

rsync -va ~/music /media/backup
