#!/usr/bin/env bash

# music-tree: store a backup representation of the music directory using `tree`

music_dir="${HOME}/music"
music_txt="${HOME}/music.txt"

if which tree > /dev/null; then
	tree -d --charset ascii --noreport -o ${music_txt} ${music_dir}
else
	echo 'Fatal: no `tree` utility.' > ${music_txt}
	exit 1
fi
