#!/usr/bin/env bash

# netflix: open google-chrome to netflix.com.
# this used to be an alias, but i want it to show up in dmenu.

function installed() {
	cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

function notify() {
	local notify_cmd="xmessage -center -timeout 3 '${*}'"

	if installed zenity; then
		notify_cmd="zenity --info --timeout=3 --text='${*}'"
	fi

	if installed notify-send; then
		notify_cmd="notify-send --expire-time=3000 info '${*}'"
	fi

	eval "${notify_cmd}" &
}

installed google-chrome || { notify "$(basename "${0}") needs 'google-chrome'." ; exit 1 ; }

google-chrome --app="https://netflix.com" >/dev/null 2>&1
