#!/usr/bin/env bash

# open-pdf: open PDF(s) in mupdf using zenity

installed() {
  cmd=$(command -v "${1}")

  [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
  return ${?}
}

notify() {
  notify_cmd="xmessage -center -timeout 3 '${*}'"

  if installed zenity; then
    notify_cmd="zenity --info --timeout=3 --text='${*}'"
  fi

  if installed notify-send; then
    notify_cmd="notify-send --expire-time=3000 info \"${*}\""
  fi

  eval "${notify_cmd}"
}

die-notify() {
  notify "Error: $*"
  exit 1
}

ensure() {
  "$@" \
    || die-notify "open-pdf: Failed to run '$*'."
}

quiet() {
  "${@}" 2>/dev/null
}

pickpdfs() {
  quiet zenity --file-selection --multiple --file-filter="*.pdf" | tr "|" "\n"
}

ensure installed zenity
ensure installed mupdf

pdfs=$(pickpdfs)

[[ -z "${pdfs}" ]] && exit

while read pdf; do
  mupdf "${pdf}" &
done <<< "${pdfs}"

