#!/usr/bin/env bash

# osx-vnc-password: output the password to OS X's built-in VNC server
# http://hints.macworld.com/article.php?story=20071103011608872

pref=/Library/Preferences/com.apple.VNCSettings.txt

[[ $(uname -s) = "Darwin" ]] || { echo "OS X only, dummy." ; exit 1 ; }
[[ -f "${pref}" ]] || { echo "Missing ${pref} to decode." ; exit 1 ; }

sudo cat /Library/Preferences/com.apple.VNCSettings.txt \
	| perl -wne \
		'BEGIN {
			@k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA"
		};
		chomp;
		@p = unpack "C*", pack "H*", $_;
		foreach (@k) {
			printf "%c", $_ ^ (shift @p || 0)
		};
		print "\n"'
