#!/usr/bin/env bash

# haste.sh - post files to hastebin and print a link. requires curl.
# usage: haste.sh <file> or pipe into haste
# ----
# Author: William Woodruff
# Licensed under the MIT License: http://opensource.org/licenses/MIT

if [[ -z "${1}" || "${1}" = "-" ]] ; then
	file="-"
elif [[ -f "${1}" ]] ; then
	file="${1}"
else
	echo "Usage: $0 <file>"
	exit 1
fi

curl -F "sprunge=<${file}" http://sprunge.us
