#!/usr/bin/env bash

# mpv-xclip: play the resource currently in the X clipboard
# this resource will usually be a URL, file path, or something like that

function installed {
	cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

function die-notify {
	notify-send "play-xclip" "${1}"
	exit 1
}

installed xclip || die-notify "missing xclip"

contents="$(xclip -o)"
if [[ -n "${contents}" ]]; then
	notify-send "play-xclip" "playing ${contents}"
	~/scripts/play "${contents}"
else
	die-notify "no resource to play"
fi
