#!/usr/bin/env bash

# mpv-xclip: play the resource currently in the X clipboard
# this resource will usually be a URL, file path, or something like that

function installed {
	local cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

# make sure we have both of our dependencies
if installed "xclip" ; then
	if xclip -o 2>&1 > /dev/null ; then
		resource=$(xclip -o)
		if [[ ! -z "${resource}" ]]; then
			notify-send --urgency=critical "play-xclip" "Playing ${resource}"
			play "${resource}"
		else
			notify-send --urgency=critical "play-xclip" "No resource to play."
		fi
	else
		notify-send --urgency=critical "play-xclip" "No resource to play."
	fi
else
	notify-send --urgency=critical "play-xclip" "xclip is needed."
fi
