#!/usr/bin/env bash

# screenlock: lock the screen with i3lock and a blurred screenshot

# modified from https://gist.github.com/csivanich/10914698
# i3lock blurred screen inspired by /u/patopop007 and the blog post
# http://plankenau.com/blog/post-10/gaussianlock

# Dependencies:
# imagemagick
# i3lock

initial=/tmp/i3lock.jpg
transform=/tmp/i3lock.png

# note: for whatever reason, `maim`'s JPG performance is way better than its PNG performance
maim --format=jpg "${initial}"
convert "${initial}" -scale "10%" -scale "1000%" "${transform}"
i3lock -e -f -i "${transform}"
rm -f "${initial}" "${transform}"
