#!/usr/bin/env bash

# slopcast: record a selected screen region
# stolen and modified from SirCmpwn's dotfiles

read -r X Y W H < <(slop -f "%x %y %w %h")

ffmpeg -f x11grab -s "${W}"x"${H}" -i :0.0+"${X}","${Y}" -pix_fmt yuv420p slopcast.mp4
