#!/usr/bin/env bash

# speaker: connect to my bluetooth speaker

installed() {
	cmd=$(command -v "${1}")

	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

die() {
	echo "Error: $*" >&2
	exit 1
}

ensure() {
	"$@" \
		|| die "Failed to run '$*'. Aborting."
}

ensure installed kbsecret
ensure installed a2dp

eval "$(ensure kbsecret env -s keys bluetooth-speaker-mac)"

a2dp "${BLUETOOTH_SPEAKER_MAC}"
