#!/usr/bin/env ruby

require "open-uri"
require "json"
require "open3"

URL = "https://www.reddit.com/r/%{subreddit}/hot.json?limit=100"

subreddit = ARGV.shift || "videos"
url = URL % { subreddit: subreddit }

begin
  data = JSON.parse(open(url).read)
  url_blobs = data["data"]["children"].select { |c| c["kind"] == "t3" }
  urls = url_blobs.map { |c| c["data"]["url"] }
rescue Exception => e
  abort("Something exploded: #{e.to_s}.")
end

abort("No URLs to play.") if urls.empty?

`echo -e "#{urls.join("\n")}" | mpv --playlist=-`
