#!/usr/bin/env bash

TEPM_CONFIG="${HOME}/.tepmrc"

# override these in ${TEPM_CONFIG}
TEPM_KERN="$(uname -s)"
TEPM_ARCH="$(uname -m)"
TEPM_BIN="${HOME}/bin"
TEPM_MAN="${HOME}/man"

function installed() {
	local cmd=$(command -v "${1}")

	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

function available() {
	type -t "${1}" > /dev/null
	return ${?}
}

function confirm() {
	printf "${*} (y/N): " && read ans

	[[ -n "${ans}" && "${ans}" =~ [Yy] ]]
	return ${?}
}

function fatal() {
	printf "Fatal: ${*}\n"
	exit 1
}

function usage() {
	printf "Usage: $(basename ${0}) <command>\n"
	printf "Available commands are:\n"
	tepm_commands
	exit 1
}

function precheck() {
	[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && fatal "bash 4.0 or later is required."

	# don't bother checking POSIX utilities
	local deps=(scp sha256sum)

	for dep in "${deps[@]}"; do
		installed "${dep}" || fatal "tepm needs '${dep}' to operate."
	done

	mkdir -p "${TEPM_BIN}" "${TEPM_MAN}"
}

function load_config() {
	if [[ ! -f "${TEPM_CONFIG}" ]]; then
		fatal "No configuration file found. Run 'tepm config' to generate one."
	fi

	source "${TEPM_CONFIG}"
	[[ -z "${TEPM_USER}" ]] && fatal "TEPM_USER missing, rerun 'tepm config'."
	[[ -z "${TEPM_HOST}" ]] && fatal "TEPM_HOST missing, rerun 'tepm config'."
}

function sftp_ls() {
	files=$(printf "ls -l tepm/${1}" | sftp -b - "${TEPM_USER}@${TEPM_HOST}")
	ret=${?}
	printf "${files}" | sed '1d' | awk '{ print $9 }'

	return ${ret} # return code masking sucks
}

function scp_fetch() {
	echo "${TEPM_USER}@${TEPM_HOST}:/home/${TEPM_USER}/tepm/${1}"
	scp -r "${TEPM_USER}@${TEPM_HOST}:/home/${TEPM_USER}/tepm/${1}" "${2}"
}

function tepm_commands() {
	local functions=($(declare -F | awk '{ print $3 }' | grep 'tepm'))
	for func in "${functions[@]}"; do
		printf "${func#tepm_}\n"
	done
}

function tepm_config() {
	if [[ -f "${TEPM_CONFIG}" ]]; then
		confirm "Overwrite existing configuration?" || exit 0
	fi

	printf "To install packages, tepm uses SSH sessions.\n"
	printf "As such, it requires a username to log in with and a host.\n"
	printf "Enter a username for tepm to connect with: "
	read tepm_user
	printf "Enter a hostname for tepm to connect with: "
	read tepm_host

	printf "TEPM_USER='${tepm_user}'\n" > "${TEPM_CONFIG}"
	printf "TEPM_HOST='${tepm_host}'\n" >> "${TEPM_CONFIG}"
}

function tepm_pkg() {
	[[ -d "${1}" ]] || fatal "A directory is required to create packages."

	pushd . > /dev/null
	cd "${1}"

	for subdir in *; do
		if [[ "${subdir}" != "bin" && "${subdir}" != "man" ]]; then
			fatal "An unrecognized subdirectory '${subdir}' was encountered."
		fi
	done

	sha256sum */* > checksums

	popd > /dev/null
}

function tepm_list() {
	if ! pkgs=$(sftp_ls "${TEPM_KERN}/${TEPM_ARCH}"); then
		fatal "Couldn't list packages (no connection or missing directories)."
	fi

	printf "${pkgs}\n"
}

function tepm_install() {
	local work_dir=$(mktemp -d "${HOME}/.tepm_XXX")
	if ! scp_fetch "${TEPM_KERN}/${TEPM_ARCH}/${1}" "${work_dir}"; then
		rm -rf "${work_dir}"
		fatal "Couldn't fetch package (no connection or missing directories)."
	fi

	pushd . > /dev/null
	cd "${work_dir}/${1}"

	if ! sha256sum --status -c checksums; then
		rm -rf "${work_dir}"
		fatal "Checksum failure during installation of '${1}'".
	fi

	cp bin/* "${TEPM_BIN}"

	for manpage in man/*; do
		local suffix="${manpage#*.}"
		mkdir -p "${TEPM_MAN}/man${suffix}"
		cp "${manpage}" "${TEPM_MAN}/man${suffix}"
	done

	popd > /dev/null
	rm -rf "${work_dir}"
}

function tepm_uninstall() {
	# to uninstall, all we need to do is fetch the checksums file and parse it
	local work_dir=$(mktemp -d "${HOME}/.tepm_XXX")
	if ! scp_fetch "${TEPM_KERN}/${TEPM_ARCH}/${1}/checksums" "${work_dir}"; then
		rm -rf "${work_dir}"
		fatal "Couldn't fetch package (no connection or missing directories)."
	fi

	pushd . > /dev/null
	cd "${work_dir}"

	local bins=$(cat checksums | awk '{ print $2 }' | grep '^bin/')
	local mans=$(cat checksums | awk '{ print $2 }' | grep '^man/')

	cd "${HOME}"
	rm "${bins}"

	for manpage in "${mans}"; do
		manpage=$(basename "${manpage}")
		local suffix="${manpage#*.}"
		rm "${TEPM_MAN}/man${suffix}/${manpage}"
	done

	popd > /dev/null
	rm -rf "${work_dir}"
}

function tepm_help() {
	usage
}

precheck

[[ -z "${1}" ]] && usage

cmd="${1}" && shift

[[ "${cmd}" != "config" ]] && load_config

if available tepm_${cmd}; then
	tepm_${cmd} $@
else
	printf "No such command: ${cmd}\n"
fi
