#!/usr/bin/env bash

# todo: a wrapper over kbsecret + todo records

SESSION="${SESSION:-todos}"

green() {
	echo -e "\e[32m${*}\e[0m"
}

yellow() {
	echo -e "\e[33m${*}\e[0m"
}

red() {
	echo -e "\e[31m${*}\e[0m"
}

die() {
	echo "Error: $*" >&2
	exit 1
}

installed() {
	cmd=$(command -v "${1}")

	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

ensure() {
	"$@" \
		|| die "Failed to run '$*'. Aborting."
}

sanity-checks() {
	ensure installed kbsecret
}

session-call() {
	cmd="${1}" ; shift
	ensure kbsecret "${cmd}" -s "${SESSION}" "${@}"
}

usage() {
	cat <<-EOS
		Usage: todo <subcommand>

		Subcommands:
		  help
		  list [--plain]
		  prune [--interactive]
		  new <label> <message>
		  rm <label>
		  show <label>
		  start <label>
		  suspend <label>
		  complete <label>
	EOS
}

list-todos() {
	if [[ "${1}" = "--plain" ]] ; then
		session-call list -t todo
	else
		completed="$(session-call todo-list --detail completed)"
		suspended="$(session-call todo-list --detail suspended)"
		started="$(session-call todo-list --detail started)"
		[[ -n "${completed}" ]] && green "${completed}"
		[[ -n "${suspended}" ]] && yellow "${suspended}"
		[[ -n "${started}" ]] && red "${started}"
	fi
}

prune-todos() {
	[[ "${1}" = "--interactive" ]] && rmflag="-i" ; shift

	for todo in $(session-call todo-list completed) ; do
		session-call rm "${rmflag}" "${todo}"
	done
}

new-todo() {
	label="${1}" ; shift
	message="${*}"
	session-call new todo "${label}" "${message}"
}

remove-todo() {
	session-call rm "${1}"
}

dump-todo() {
	session-call dump-fields "${1}"
}

mark-todo() {
	mark="${1}"
	label="${2}"
	session-call todo "${mark}" "${label}"
}

not-found() {
	echo "todo: no such command: '${1}'"
}

sanity-checks

cmd="${1:-help}" ; shift

case "${cmd}" in
	--help|-h|help ) usage ; exit ;;
	ls|list ) list-todos "${@}" ;;
	pr|prune ) prune-todos "${@}" ;;
	n|new ) new-todo "${@}" ;;
	rm ) remove-todo "${@}" ;;
	dump|show ) dump-todo "${@}" ;;
	start|suspend|complete ) mark-todo "${cmd}" "${@}" ;;
	* ) not-found "${cmd}" ; usage ; exit 1 ;;
esac
