#!/usr/bin/env bash

# twitch: stream to twitch
# adapted from https://wiki.archlinux.org/index.php/Streaming_using_twitch.tv

encoder="ffmpeg"

function installed() {
	local cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

function error() {
	>&2 printf "Fatal: ${@}. Exiting.\n"
	exit 2
}

installed "${encoder}" || error "Missing dependency: '${encoder}'"

inres="1366x768" # input resolution
outres="1366x768" # output resolution
fps="15" # target FPS
gop="30" # i-frame interval, should be double of FPS,
gopmin="15" # min i-frame interval, should be equal to fps,
threads="2" # max 6
cbr="1000k" # constant bitrate (should be between 1000k - 3000k)
quality="fast"  # one of the many FFMPEG presets
audio_rate="44100"
stream_key="$TWITCH_API_KEY"
server="live-iad" # see http://bashtech.net/twitch/ingest.php for list

ffmpeg -f x11grab -s "${inres}" -r "${fps}" -i :0.0 -f alsa -i pulse -f \
    flv -ac 2 -ar $audio_rate -vcodec libx264 -g "${gop}" -keyint_min \
    "${gopmin}" -b:v "${cbr}" -minrate "${cbr}" -maxrate "${cbr}" -pix_fmt \
    yuv420p -s "${outres}" -preset "${quality}" -tune film -acodec libmp3lame \
    -threads $threads -strict normal -bufsize "${cbr}" \
    "rtmp://$server.twitch.tv/app/$stream_key"
