#!/usr/bin/env bash

# update: catch-all update script

function installed() {
	cmd=$(command -v "${1}")

	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

function prompt {
	echo -n "${1} (y/N): " && read ans
	[[ "$ans" =~ [Yy] ]]
	return ${?}
}

function do_snap {
	sudo snap refresh
}

function do_apt {
	sudo apt update
	sudo apt upgrade
	sudo apt dist-upgrade
	sudo apt autoremove
	sudo apt clean
}

function do_pacman {
	sudo pacman -Syyu
}

function do_brew {
	brew -v update
	brew -v upgrade
	brew cleanup -s
}

[[ "$(uname)" = "Linux" ]] && installed apt && do_apt
[[ "$(uname)" = "Linux" ]] && installed snap && do_snap
[[ "$(uname)" = "Linux" ]] && installed pacman && do_pacman
installed brew && do_brew
