#!/usr/bin/env bash

# update: catch-all update script for OS X and some Linux distros

function installed() {
	local cmd=$(command -v "${1}")

	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

system=$(uname)

if [[ "$system" = "Darwin" ]] ; then
	if installed brew ; then
		brew -v update
		brew -v upgrade
		brew cleanup -s
	else
		echo "Homebrew not installed."
	fi
elif [[ "$system" = "Linux" ]] ; then
	if installed apt-get ; then
		sudo apt-get -qq update
		sudo apt-get upgrade
		sudo apt-get autoremove
		sudo apt-get clean
	elif installed pacman ; then
		sudo pacman -Syyu
	else
		echo "Package manager unsupported."
	fi
fi

if installed gem ; then
	printf "Update Ruby gems? (y/N): " && read ans
	if [[ "$ans" =~ [Yy] ]] ; then
		sudo gem update
	fi
fi

if installed cpan ; then
	printf "Update CPAN modules? (y/N): " && read ans
	if [[ "$ans" =~ [Yy] ]] ; then
		sudo cpan -u
	fi
fi

if installed npm ; then
	printf "Update NPM packages? (y/N): " && read ans
	if [[ "$ans" =~ [Yy] ]] ; then
		npm update
	fi
fi

if installed pip ; then
	printf "Update Python packages? (y/N): " && read ans
	if [[ "$ans" =~ [Yy] ]] ; then
		# http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip
		pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | sudo xargs -n1 pip install -U
	fi
fi
