#!/usr/bin/env bash

# workspaces-janus: set up my workstation workspaces

# no matter what i do, these files keep reappearing and cause subl to spawn a
# bunch of windows, trashing the layout below.
rm -rf ~/.config/sublime-text/Local/*.sublime_session

xset dpms force on

yad --title="Load workspaces?" || exit

# This is split up so that I can cancel kbs2 without subsequent commands failing.
kbs2 agent && kbs2 agent unwrap
kbs2 agent query && kbs2 ssh-add janus-ssh-key
kbs2 agent query && kbs2 gpg-add personal-gpg-passphrase

sleep 0.1
i3-msg 'workspace 2A; append_layout ~/.config/i3/workspaces/2A.json'
sleep 0.1
i3-msg 'exec --no-startup-id "alacritty --title mutt --class mutt -e bash -c \"cd ~/Downloads; neomutt\""'
sleep 0.1

sleep 0.1
i3-msg 'workspace 1A; append_layout ~/.config/i3/workspaces/1A.json'
sleep 0.1
i3-msg 'exec --no-startup-id subl'
sleep 0.1

sleep 0.1
i3-msg 'workspace 1B; append_layout ~/.config/i3/workspaces/1B.json'
i3-msg 'exec --no-startup-id alacritty'
i3-msg 'exec --no-startup-id hexchat'
i3-msg 'exec --no-startup-id firefox'
sleep 0.1

i3-msg 'workspace 1A'
i3-msg 'workspace 1B'

ezsshfs athena
ezsshfs arabella
