#!/usr/bin/env bash

# workspaces-mercury: set up my mobile workspaces

# no matter what i do, these files keep reappearing and cause subl to spawn a
# bunch of windows, trashing the layout below.
rm -rf ~/.config/sublime-text/Local/*.sublime_session

yad --title="Load workspaces?" --timeout=5 || exit

# This is split up so that I can cancel kbs2 without subsequent commands failing.
kbs2 agent && kbs2 agent unwrap
kbs2 agent query && kbs2 ssh-add mercury-ssh-key
kbs2 agent query && kbs2 gpg-add personal-gpg-passphrase

i3-msg 'rename workspace 1 to 1 www'

i3-msg 'workspace 1 www; append_layout ~/.config/i3/workspaces/www.json'
i3-msg 'exec --no-startup-id firefox'

i3-msg 'workspace 2 dev; append_layout ~/.config/i3/workspaces/dev.json'
i3-msg 'exec --no-startup-id subl'
i3-msg 'exec --no-startup-id alacritty'

i3-msg 'workspace 3 com; append_layout ~/.config/i3/workspaces/com.json'
i3-msg 'exec --no-startup-id hexchat'
i3-msg 'exec --no-startup-id "alacritty --title mutt --class mutt -e bash -c \"cd ~/Downloads; neomutt\""'

i3-msg 'workspace 1 www'

ezsshfs athena
ezsshfs arabella
