#!/usr/bin/env bash

# worldtimes: local times around the world
# derived from isislovecruft/scripts/world_time (github)

datetime="date +%H:%M"

printf "NYC:\t%s\n" "$(TZ="America/New_York" ${datetime})"
printf "SF:\t%s\n" "$(TZ="America/Los_Angeles" ${datetime})"
printf "London:\t%s\n" "$(TZ="Europe/London" ${datetime})"
printf "Paris:\t%s\n" "$(TZ="Europe/Paris" ${datetime})"
printf "Berlin:\t%s\n" "$(TZ="Europe/Berlin" ${datetime})"
printf "Tokyo:\t%s\n" "$(TZ="Asia/Tokyo" ${datetime})"
