#!/usr/bin/env bash

rm -rf ~/website/www/*
cp -r /usr/share/nginx/html/* ~/website/www/
pushd . > /dev/null
cd ~/website
git add .
git commit -m "scripted backup at $(date)"
popd > /dev/null

exit 0
