#!/usr/bin/env bash

# ytsearch2: take a search query from dmenu, feed it into youtube-dl,
# extract the thumbnails and display them in feh, and play the urls corresponding
# to the user's selections in mpv

query=$(dmenu -p youtube < /dev/null 2> /dev/null)

[[ -z "${query}" ]] && exit 1

# Look upon my pipeline, and weep.
# TODO: Use -K to add captions.
youtube-dl -j "ytsearch4:${query}" \
    | jq -r ".thumbnail" \
    | feh -s -y 200 -E 300 -t --index-info '' -A 'echo %F' -f - \
    | sed -n 's|.*vi.*/\(.*\)/.*|https://youtu.be/\1|p' \
    | mpv --playlist=-
